# Generated by Django 4.2.1 on 2025-11-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='role',
        ),
    ]
