# Generated by Django 4.2.1 on 2025-11-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_notification_role_primesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='primesubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=10),
        ),
    ]
